import commands.wordle_play
import commands.ttt_play
import commands.search_in_google
import commands.add_task
import commands.change_task
import commands.delete_task
import commands.change_name
import commands.change_city
import commands.main_menu
import commands.user_profile
import commands.diary
import commands.weather_now
import commands.weather_5_days
import commands.games
import commands.games_statistics
import commands.tasks_notifications
import commands.morning_notifications
import commands.helps
import commands.not_found
